<!-- REST CLIENTS FOR CHECKING -->

### Get all contacts
GET http://localhost:3000/contacts

###

### Get a single contact by ID
GET http://localhost:3000/contacts/678c7037be89513bea8538e2

### POST a new contact to the list
POST http://localhost:3000/contacts
Content-Type: application/json

{
  "firstName": "Orihah",
  "lastName": "Chambers",
  "email": "Orihah@example.com",
  "favoriteColor": "Red",
  "birthday": "2002-05-29"
}


### PUT Request to update a contact
PUT http://localhost:3000/contacts/678c7037be89513bea8538e4
Content-Type: application/json

{
  "firstName": "Kaylee-Ann",
  "lastName": "Foster",
  "email": "Kaylee@example.com",
  "favoriteColor": "Dark green",
  "birthday": "2006-09-03"
}

### DELETE Request to remove a contact
DELETE http://localhost:3000/contacts/679d841904085399d2eabf4b

